### ISSUE TITLE
Reporting process for harassment.

### ISSUE THREAD

**Issue by cbryantryback** [opengovfoundation/hr-manual#4]
This manual is already a step above many in that it covers harassment in more detail, instead of just plopping down "etc etc prohibited by law", but there's no mention of what steps to take to report harassment. As an employee, knowing that there's a basic process in place at my own company makes me feel safer and more confident that issues will be addressed appropriately by all parties. I don't know enough about your particular setup, so I can't go as far as a PR for suggested language, but for small businesses/orgs, where there's not an HR manager, I've seen some policies that basically say the following:
1. Issues should be reported to a direct supervisor.
2. If that would be awkward for reasons, issues should be reported to whoever is next highest up.
3. Issues will be investigated [they may or may not say who exactly investigates] and there will be appropriate follow-up [they may or may not detail what that would be].

IANAL of course, but from my perspective, this policy seems like a good example of language to that effect, aside from stating that an HR manager would ultimately be responsible for investigating. 
- http://www.aura-astronomy.org/about/policies/Section%20B/B25%29%20B-XXV-Standards%20of%20Workplace%20Conduct.pdf

**Comment by krusynth** [comment]
Thanks @cbryantryback, this is great feedback!

Team, I asked @cbryantryback to repost her comments she made privately on here. I think update the language this way would be a step in the right direction.
